---
- name: Install Apache Packages on Ubuntu
  apt: name=apache2 state=present
  when: ansible_os_family == "Debian"

- name: Start the Apache Service on Ubuntu
  service: name=apache2 state=started 
  when: ansible_os_family == "Debian"

- name: Install Apache Packages on Redhat
  yum: name=httpd state=present
  when: ansible_os_family == "RedHat"

- name: Start the Apache Service on Redhat
  service: name=httpd state=started 
  when: ansible_os_family == "RedHat"

- name: Checking the Document Root
  command: ls {{http_doc}}
  register: result1
  ignore_errors: yes

- debug: msg="Unable to fine Document Root"
  when: result1|failed

- name: Create New Document Root as specified.
  file: path={{http_doc}} state=directory
  when: result1|failed

- name: Deploy Apache Custom Configuration 
  template: src=templates/apache2.j2 dest=/etc/apache2/apache2.conf
  notify:
    - Restart Apache2

- name: Force the Handlers
  meta: flush_handlers

- name: Downlaod Background Image.
  get_url: url="https://celb.lu/wp-content/uploads/2014/04/Gray-plain-website-background-1024x576.jpg" dest={{http_doc}}/back.jpg mode=0755

- name: Deploy Dynamic WebPage. 
  template: src=templates/info.j2 dest={{http_doc}}/info.html
  notify: 
    - Restart Apache2

- name: Deploy Static WebPage. 
  copy: src=files/index.html dest={{http_doc}}/index.html

- debug: msg="The Username you supplied at prompt is :{{username}}"
